version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/telemetry-challenge-database?sslmode=disable
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations

  db:
    image: postgres:15-alpine
    container_name: telemetry-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telemetry-challenge-database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: